name: Custom CLI image Test

on: workflow_dispatch

jobs: 
  build: 
    runs-on: ubuntu-latest
    container:
      image: jbsnyk/jbsnykcustom:latest
      options: --platform linux/amd64
      
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: snyk code test and snyk to HTML 
        run: snyk code test --json | snyk-to-html -o results-code.html

      - name: upload snyk HTML report 
        uses: actions/upload-artifact@v3
        with:
          name: snyk-html-report
          path: results-code.html
